// <auto-generated />
using KDT.SimpleDiff.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KDT.SimpleDiff.Migrations
{
    [DbContext(typeof(SimpleDiffDbContext))]
    partial class SimpleDiffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("KDT.SimpleDiff.Entities.Diff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diffs", "SimpleDiff");
                });
#pragma warning restore 612, 618
        }
    }
}
